apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-server
  labels:
    app: zip-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zip-server
  template:
    metadata:
      labels:
        app: zip-server
    spec:
      containers:
        - name: zip-server
          image: neeraj010702/zip-server:latest  # Change to your actual Docker Hub image
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: zip-storage
              mountPath: /data  # This is where the server reads files from inside the container
      volumes:
        - name: zip-storage
          hostPath:
            path: /c/Users/Public/Downloads/DATA_Files  # Path format for Docker on Windows
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: zip-server-service
spec:
  selector:
    app: zip-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
