apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zip-server
  template:
    metadata:
      labels:
        app: zip-server
    spec:
      containers:
        - name: zip-server
          image: neeraj010702/zip-server:latest
          ports:
            - containerPort: 5000
          env:
            - name: ZIP_DIR
              value: "/data"
          volumeMounts:
            - mountPath: /data
              name: zip-volume
      volumes:
        - name: zip-volume
          hostPath:
            path: /mnt/data
            type: DirectoryOrCreate
