apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zip-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - yourdomain.com
      secretName: tls-secret   # Correct secret name here
  rules:
    - host: yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zip-server-service
                port:
                  number: 80
