apiVersion: v1
kind: Service
metadata:
  name: zip-server-service
spec:
  selector:
    app: zip-server
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 5000  # container port
      nodePort: 30080   # fixed node port in 30000-32767 range
  type: NodePort
