apiVersion: v1
kind: Service
metadata:
  name: zip-server-service
spec:
  selector:
    app: zip-server
  ports:
    - protocol: TCP
      port: 80              # Port exposed inside cluster
      targetPort: 5000      # Container port
  type: ClusterIP          # Expose only inside cluster
